install:
  - set QTDIR=C:\Qt\5.11.3\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake QuickWindow.pro
  - mingw32-make
  - cd bin
  - 7z a ../QuickWindow.zip *

artifacts:
  - path: QuickWindow.zip
