jobs:
- job: win32_qt4
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      bash generate.sh win32
      cd ../s
      sh build.sh qt4 win32
  - publish: $(System.DefaultWorkingDirectory)/bin
    artifact: QuickWindow-win32-qt4

- job: win32_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      bash generate.sh win32
      cd ../s
      sh build.sh qt5 win32
  - publish: $(System.DefaultWorkingDirectory)/bin
    artifact: QuickWindow-win32-qt5

- job: win64_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      bash generate.sh win64
      cd ../s
      sh build.sh qt5 win64
  - publish: $(System.DefaultWorkingDirectory)/bin
    artifact: QuickWindow-win64-qt5
