jobs:
- job: windows_amd64
  steps:
  - bash: |
      cd ..
      wget http://omega.gg/get/Sky/3rdparty/win64 -O 3rdparty-win64.zip
      unzip 3rdparty-win64.zip
      cd QuickWindow
      sh build.sh win64
