jobs:
- job: win32_qt4
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty-win32.zip http://omega.gg/get/Sky/3rdparty/win32
      unzip 3rdparty-win32.zip
      cd s
      sh build.sh qt4 win32
  - publish: $(System.DefaultWorkingDirectory)/bin
    artifact: QuickWindow-win32-qt4

- job: win32_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty-win32.zip http://omega.gg/get/Sky/3rdparty/win32
      unzip 3rdparty-win32.zip
      cd s
      sh build.sh qt5 win32
  - publish: $(System.DefaultWorkingDirectory)/bin
    artifact: QuickWindow-win32-qt5

- job: win64_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty-win64.zip http://omega.gg/get/Sky/3rdparty/win64
      unzip 3rdparty-win64.zip
      cd s
      sh build.sh qt5 win64
  - publish: $(System.DefaultWorkingDirectory)/bin
    artifact: QuickWindow-win64-qt5
