jobs:
- job: windows_amd64
  pool:
    vmImage: 'windows-latest'
  steps:
  - bash: |
      cd ..
      wget http://omega.gg/get/Sky/3rdparty/win64 -O 3rdparty-win64.zip
      unzip 3rdparty-win64.zip
      cd s
      sudo sh build.sh qt5 win64
