jobs:
- job: windows_amd64
  pool:
    vmImage: 'windows-latest'
  steps:
  - bash: |
      cd ..
      curl -l -o 3rdparty-win64.zip http://omega.gg/get/Sky/3rdparty/win64
      unzip 3rdparty-win64.zip
      cd s
      sudo sh build.sh qt5 win64
